### ISSUE TITLE
Time taken for carbon removal as a metric

### ISSUE THREAD

**Issue by Emlitt** [carbonplan/cdr-database#219]
Hello CarbonPlan,
This database is fantastic, thank you so much for providing this.
One of the main issues I have when considering carbon removal projects for clients is the time taken for a tonne of carbon dioxide to be removed.
For example, a lot of afforestation / tree-planting projects and other nature-based solutions are calculated over the lifetime of the tree.  So if a tree takes 50 years to sequester 1 tonne, the price of the 1 tonne of carbon reflects purchasing that 1 tree, but there is no factoring in the time.  Companies therefore claim that that 1 tonne has been dealt with / neutralised, whereas in fact it won't be absorbed for another 50 years.  This is what I call 'carbon debt' and is a big problem with so-called offsets.

With CDR projects such as Climeworks, when you pay for 1 tonne of removals that tonne will be gone within a year, approximately, allowing for the administration and backlog etc of the company.

Therefore, could you add in an additional metric which is called something like 'time to removal' or 'removal speed'?

As time is of the essence for climate change retardation, I think this is a crucial aspect when weighing up projects to invest in.

Thanks so much!

Emma Littlewood (Green Element and Compare Your Footprint).

**Comment by freyac** [comment]
Hi Emma, 

Thanks for raising this issue, and apologies for the slow response. We totally agreed that the timeline of proposed offsetting solutions is important for understanding their climate impacts. 

When a removal timeline is clearly represented in a project’s proposal, we try to include it in the volume notes (e.g. see [this entry](https://carbonplan.org/research/cdr-database/project?id=STRP041)). But often, the timeline associated with the offered removal is ambiguous. This is frequently the case for forest and soil projects, as the offered credits are not usually clearly vintaged. For these projects, you might reference the project lifetime included in the Permanence comment (e.g. see [this entry](https://carbonplan.org/research/cdr-database/project?id=MSFT024)), which is equivalent to the range of possible removal dates. 

Of course, understanding when a removal happens is just one piece of the puzzle. In our minds, how long removed carbon will be stored (i.e. the permanence metric) is much more important for understanding how a project will contribute to net zero goals, cumulative carbon emissions, and long-term warming.

Thanks again for your note, and we’ll think about how we can more consistently represent the information you’re hoping to find. 

Freya

**Comment by freyac** [comment]
Closing this issue for now. Thanks again for reaching out, Emma!
