### ISSUE TITLE
Zenodo integration

### ISSUE THREAD

**Issue by jhamman** [carbonplan/cdr-database#231]
We should set up Zenodo's github integration to generate DOIs for this project. We didn't make releases/tags for previous versions but @freeman-lab and I came up with our best estimates for what they would be: 

1.0.0 -> 5/18/2020 -> 95e4383b447d693a8d06dd2895a43ca1f5ff74b2
1.1.0 -> 3/16/2021 -> 5c60a8371c00281388d019a346e24512925fe035
1.2.0 -> 5/26/2021 -> 3372072abf5d07a29d6cf480db78642f3bf4a596

**Comment by jhamman** [comment]
One question I have is whether we want to archive the full github repository, including but not limited to the dataset or only the dataset. The former is quite a bit easier to do but would also include a bunch of JS/React things that most data users wouldn't care about. Thoughts @freyac / @freeman-lab?

**Comment by freyac** [comment]
No strong opinions, but it seems to me that if the main utility of a doi is to allow people to definitively point to where the data came from, I don't see extra stuff being included alongside the data as a big cost.

**Comment by freeman-lab** [comment]
I think I feel similarly as @freyac. If people are using this to _access_ the data then it's definitely cleaner to just have the data files, but if it's mainly about being able to point to a version of record for citation purposes, the repository seems fine. Also as a flag, we changed where in the repo the data is stored across the versions, but in all three cases it's indeed in the repo. No concerns there, just making a note of it.

**Comment by jhamman** [comment]
Great. Let's start simple then and just go with tagged releases which translate 1:1 to Zenodo archives.
