### ISSUE TITLE
axis label fonts should be in secondary color

### ISSUE THREAD

**Issue by jhamman** [carbonplan/cdr-database#58]
Current:

![image](https://user-images.githubusercontent.com/2443309/88597452-151b6500-d01c-11ea-8fae-fbd996ed93b4.png)

Design mock:

![image](https://user-images.githubusercontent.com/2443309/88597345-e8ffe400-d01b-11ea-87c6-448c0ae77cfd.png)

**Comment by freeman-lab** [comment]
closing as this is effectively addressed in the new design
